### ISSUE TITLE
We Can Add Issues Here Under the Issues tab

### ISSUE THREAD

**Issue by blulady** [wardini/SDPySummerJam#1]
https://github.com/wardini/SDPySummerJam/issues/

**Comment by wardini** [comment]
some of the constellations seemed weird and I was trying to figure things out.   But then I discovered there is an international astronomical union that publishes the "standard" for the constellations.  The skymap.org web site for some reason does not use those.   Anyway, the constellation for Gemini makes a lot more sense after working with constellations found on this web page:
https://www.iau.org/static/public/constellations/pdf/ORI.pdf

**Comment by wardini** [comment]
the Orion image is flipped left to right.   I wonder if it was painted from the perspective of looking down on the Earth.  Strange that it exists this way.  I really just want the figure in the middle with the remainder transparent.

**Comment by wardini** [comment]
Here is my latest success.  will this image show up?

![capricornus](https://github.com/wardini/SDPySummerJam/assets/446243/85af71a2-a67b-41b8-ad1b-0b5bf4cb04f5)

**Comment by wardini** [comment]
Another success
![aquarius](https://github.com/wardini/SDPySummerJam/assets/446243/7b588fc3-7c42-465f-998b-7ff0515aae84)

**Comment by wardini** [comment]
I am amazed how well those last two lined up with an actual star map.

**Comment by wardini** [comment]
![aquarius](https://github.com/wardini/SDPySummerJam/assets/446243/f1055256-d20e-404f-9622-a7ee1f12650a)

**Comment by wardini** [comment]
![orion](https://github.com/wardini/SDPySummerJam/assets/446243/45f340d0-8e64-4c4d-8bde-c54ff664b2bc)

**Comment by wardini** [comment]
![pegasus](https://github.com/wardini/SDPySummerJam/assets/446243/91b7aed3-5437-4658-8d6e-22e48a937d2e)

**Comment by wardini** [comment]
OK. I've mapped all of your images except Andromeda.   I'll try to get that star map and finish that one.

**Comment by wardini** [comment]
![andromeda](https://github.com/wardini/SDPySummerJam/assets/446243/e3dfec90-644d-4902-b815-268f93b79dd7)

**Comment by wardini** [comment]
That one didn't fit as good but definitely all the stars are there.
